'use strict';
const fs=require('fs'),assert=require('assert'),{JSDOM}=require('jsdom');
const html=fs.readFileSync(require('path').join(__dirname,'../index.html'),'utf8');
const code=html.match(/<script>([\s\S]*?)<\/script>/)[1].replace(/\(function \(\) \{\s*'use strict';/,'').replace(/\}\)\(\);\s*$/,'').replace(/  init\(\);/,'');
const dom=new JSDOM(html.replace(/<script>[\s\S]*?<\/script>/,''),{url:'https://arcade.test',runScripts:'outside-only'}),w=dom.window;
w.setTimeout=()=>0;w.requestAnimationFrame=()=>0;w.eval(code);w.loadAllSaves();w.initArcade();
let n=0;function test(name,fn){fn();n++;console.log('PASS '+name);}
const card=(r,s=0)=>({r,s});
function fresh(game='blackjack',mode='coins'){w.G.active=false;w.Arcade.round=null;w.player.arcade={stats:{},pending:null,history:[]};w.player.coins=500;w.Arcade.practice=500;w.Arcade.mode=mode;w.openArcade(game);}
function rig(cards){const shuffle=w.shuffle;w.shuffle=()=>cards.slice().reverse();return ()=>w.shuffle=shuffle;}
test('四个大厅入口，切换同页，老档余额不重置',()=>{assert.equal(w.document.querySelectorAll('[data-game]').length,4);let p=w.migratePlayer({version:13,coins:876,name:'旧玩家'});assert.equal(p.coins,876);assert.equal(p.version,14);assert(p.arcade.stats);w.document.querySelector('[data-game="blackjack"]').click();w.openArcade('blackjack');assert.equal(w.App.screen,'arcade');});
test('A软硬点数与多A降级',()=>{assert.equal(w.blackjackValue([card(14),card(14),card(9)]).total,21);assert.equal(w.blackjackValue([card(14),card(6)]).soft,true);assert.equal(w.blackjackValue([card(14),card(6),card(10)]).total,17);assert.equal(w.blackjackValue([card(14),card(6),card(10)]).soft,false);});
test('天然21点按3:2净赢且结算只能一次',()=>{fresh();const done=rig([card(14),card(13),card(9),card(8)]);w.blackjackStart(10);done();assert.equal(w.player.coins,515);assert(w.Arcade.round.done);assert.equal(w.arcadeSettle(25,'重复'),false);assert.equal(w.player.coins,515);assert.equal(w.player.arcade.stats.blackjack.hands,1);});
test('双方天然21点退本金',()=>{fresh();const done=rig([card(14),card(13),card(14),card(12)]);w.blackjackStart(20);done();assert.equal(w.player.coins,500);});
test('庄家天然21点即结算且玩家暗牌不可多操作',()=>{fresh();const done=rig([card(10),card(8),card(14),card(12)]);w.blackjackStart(20);done();w.blackjackHit(false);assert.equal(w.player.coins,480);assert.equal(w.Arcade.round.hand.length,2);});
test('软17停牌，普通21不是天然奖金',()=>{fresh();const done=rig([card(10),card(5),card(14),card(6),card(6)]);w.blackjackStart(10);w.blackjackHit(false);done();assert.equal(w.player.coins,510);assert.equal(w.Arcade.round.dealer.length,2);});
test('加倍扣两倍，只补一张并结算',()=>{fresh();const done=rig([card(5),card(6),card(10),card(7),card(10)]);w.blackjackStart(20);w.blackjackHit(true);done();assert.equal(w.Arcade.round.stake,40);assert.equal(w.Arcade.round.hand.length,3);assert.equal(w.player.coins,540);});
test('要牌后不可加倍且余额不足不可加倍',()=>{fresh();const done=rig([card(2),card(3),card(10),card(7),card(2)]);w.blackjackStart(100);w.blackjackHit(false);w.blackjackHit(true);done();assert.equal(w.Arcade.round.hand.length,3);assert.equal(w.Arcade.round.stake,100);});
test('爆牌与退出扣款不重复，练习不污染正式资产统计',()=>{fresh('blackjack','practice');const done=rig([card(10),card(9),card(10),card(7),card(10)]);w.blackjackStart(10);w.blackjackHit(false);done();assert.equal(w.Arcade.practice,490);assert.equal(w.player.coins,500);assert.equal(Object.keys(w.player.arcade.stats).length,0);});
test('返回确认取消保留本局，确认离桌记一次亏损',()=>{fresh();const done=rig([card(10),card(5),card(10),card(7)]);w.blackjackStart(20);done();w.arcadeLeave(false);assert.equal(w.document.getElementById('arcExit').hidden,false);assert(!w.Arcade.round.done);w.document.getElementById('arcExitNo').click();w.arcadeLeave(true);assert.equal(w.player.coins,480);assert.equal(w.player.arcade.stats.blackjack.net,-20);assert.equal(w.App.screen,'lobby');});
test('刷新放弃未完局不重复扣款且记录可持久',()=>{fresh();const done=rig([card(10),card(5),card(10),card(7)]);w.blackjackStart(20);done();w.Arcade.round=null;w.arcadeRecover();w.arcadeRecover();assert.equal(w.player.coins,480);assert.equal(w.player.arcade.stats.blackjack.hands,1);assert.equal(w.player.arcade.pending,null);});
test('下注失败回滚、结算失败可重试一次',()=>{fresh();const persist=w.arcadePersist;w.arcadePersist=()=>false;assert.equal(w.arcadeBegin(20),false);assert.equal(w.player.coins,500);w.arcadePersist=persist;const done=rig([card(10),card(8),card(10),card(7)]);w.blackjackStart(20);done();w.arcadePersist=()=>false;w.blackjackStand();assert.equal(w.player.coins,480);assert(w.Arcade.round.retry);w.arcadePersist=persist;w.arcadeDispatch('retry');assert.equal(w.player.coins,520);assert.equal(w.player.arcade.stats.blackjack.hands,1);});
test('炸金花牌型排序与A23最小顺子、无235特例',()=>{const triple=[card(2,0),card(2,1),card(2,2)],sf=[card(14),card(13),card(12)],flush=[card(14),card(10),card(3)],straight=[card(14,0),card(3,1),card(2,2)],pair=[card(14,0),card(14,1),card(13,2)],high=[card(14,0),card(13,1),card(10,2)];const hands=[triple,sf,flush,straight,pair,high];for(let i=0;i<5;i++)assert(w.goldCompare(hands[i],hands[i+1])>0);assert(w.goldCompare([card(4),card(3,1),card(2,2)],straight)>0);assert(w.goldCompare([card(2),card(3,1),card(5,2)],triple)<0);});
test('枚举全部22100组三张牌分布',()=>{const d=w.makeDeck(),counts=[0,0,0,0,0,0];for(let i=0;i<50;i++)for(let j=i+1;j<51;j++)for(let k=j+1;k<52;k++)counts[w.goldValue([d[i],d[j],d[k]])[0]]++;assert.deepEqual(counts,[16440,3744,720,1096,48,52]);});
test('金花初始筹码守恒、不重牌、看牌免费后跟注翻倍',()=>{fresh('gold');w.goldStart(10);const r=w.Arcade.round;assert.equal(r.pot,40);assert.equal(new Set(r.seats.flatMap(p=>p.hand.map(c=>c.r+'-'+c.s))).size,12);w.goldAction('peek');assert.equal(w.player.coins,490);const ai=w.goldAITurns;w.goldAITurns=()=>{};w.goldAction('call');w.goldAITurns=ai;assert.equal(w.player.coins,470);assert.equal(r.pot,60);assert.equal(r.stake,30);});
test('同牌比牌发起者输，第三轮前拒绝比牌',()=>{fresh('gold');w.goldStart(10);const r=w.Arcade.round;r.seats[0].hand=[card(14),card(9,1),card(3,2)];r.seats[1].hand=[card(14,1),card(9,2),card(3,3)];w.goldAction('compare',1);assert.equal(r.stake,10);r.turn=3;w.goldAction('compare',1);assert(r.seats[0].folded);assert(r.done);assert.equal(w.player.coins,480);});
test('十轮摊牌平分底池余数守恒',()=>{fresh('gold');w.goldStart(10);const r=w.Arcade.round;r.seats[2].folded=r.seats[3].folded=true;r.seats[0].hand=[card(14),card(9,1),card(3,2)];r.seats[1].hand=[card(14,1),card(9,2),card(3,3)];r.pot=41;w.goldResolve(true);assert.equal(r.payout,21);});
test('炸金花500局随机策略终止、钱包与底池守恒',()=>{fresh('gold','practice');for(let i=0;i<500;i++){w.Arcade.practice=500;w.goldStart(10);let steps=0;while(!w.Arcade.round.done&&steps++<15){const r=w.Arcade.round;w.goldAction(steps===1?'peek':w.arcadeBalance()<r.unit*(r.seats[0].seen?2:1)?'fold':'call');}const r=w.Arcade.round;assert(r.done);assert.equal(r.pot,r.seats.reduce((s,p)=>s+p.paid,0));assert(r.seats.slice(1).every(p=>p.stack>=0&&p.stack+p.paid===500));assert.equal(w.Arcade.practice,500-r.stake+r.payout);}assert.equal(w.player.coins,500);});
test('骰子216个结果：大小各105，豹子6，赔率明确',()=>{let small=0,big=0,triple=0;for(let a=1;a<=6;a++)for(let b=1;b<=6;b++)for(let c=1;c<=6;c++){small+=w.diceResult([a,b,c],'small').win;big+=w.diceResult([a,b,c],'big').win;triple+=w.diceResult([a,b,c],'big').triple;}assert.equal(small,105);assert.equal(big,105);assert.equal(triple,6);});
test('猜骰子赢、输、重复结算与下注范围',()=>{fresh('dice');const rand=w.randomInt;let seq=[123,0,1,2];w.randomInt=()=>seq.shift();w.dicePlay(20,'small');w.randomInt=rand;assert.equal(w.player.coins,520);assert.equal(w.arcadeSettle(40,'重复'),false);assert.equal(w.arcadeBegin(11),false);assert.equal(w.arcadeBegin(-10),false);});
test('2000局骰子练习不刷德州任务、段位或经验',()=>{fresh('dice','practice');const before=JSON.stringify({daily:w.player.dailyProgress,hands:w.player.totalHands,exp:w.player.exp,rank:w.player.rankPoints});for(let i=0;i<2000;i++){w.Arcade.practice=500;w.dicePlay(10,i%2?'big':'small');assert([490,510].includes(w.Arcade.practice));}assert.equal(JSON.stringify({daily:w.player.dailyProgress,hands:w.player.totalHands,exp:w.player.exp,rank:w.player.rankPoints}),before);assert.equal(w.player.coins,500);});
test('1000局21点每副不重牌、终局筹码正确',()=>{fresh('blackjack','practice');for(let i=0;i<1000;i++){w.Arcade.practice=500;w.blackjackStart(10);while(!w.Arcade.round.done){if(w.blackjackValue(w.Arcade.round.hand).total<17)w.blackjackHit(false);else w.blackjackStand();}const r=w.Arcade.round,cards=r.hand.concat(r.dealer,r.deck);assert.equal(cards.length,52);assert.equal(new Set(cards.map(c=>c.r+'-'+c.s)).size,52);assert.equal(w.Arcade.practice,500-r.stake+r.payout);}});
test('余额不足加倍和跨游戏/存档切换被拒绝',()=>{fresh();const done=rig([card(5),card(6),card(10),card(7)]);w.player.coins=10;w.blackjackStart(10);done();w.blackjackHit(true);assert.equal(w.Arcade.round.hand.length,2);assert.equal(w.Arcade.round.stake,10);assert.equal(w.openArcade('dice'),false);assert.equal(w.tryEnterGame('easy'),false);assert.equal(w.createNewSaveAt(2),false);assert.equal(w.switchToSlot(1),false);assert.equal(w.deleteSlot(1),false);});
test('金币记录跨页面重载保留，未完局只记一次',()=>{fresh();const done=rig([card(5),card(6),card(10),card(7)]);w.blackjackStart(20);done();const saved=w.localStorage.getItem(w.SAVE_KEY_ALL);const other=new JSDOM(html.replace(/<script>[\s\S]*?<\/script>/,''),{url:'https://arcade.test',runScripts:'outside-only'});other.window.setTimeout=()=>0;other.window.requestAnimationFrame=()=>0;other.window.localStorage.setItem(w.SAVE_KEY_ALL,saved);other.window.eval(code);other.window.loadAllSaves();other.window.arcadeRecover();other.window.arcadeRecover();assert.equal(other.window.player.coins,480);assert.equal(other.window.player.arcade.stats.blackjack.net,-20);assert.equal(other.window.player.arcade.stats.blackjack.hands,1);other.window.close();});
test('UI规则、练习补充、骰子按钮走实际事件',()=>{fresh('dice','practice');w.document.getElementById('arcRules').click();assert.equal(w.document.getElementById('arcHelp').hidden,false);w.document.querySelector('[data-arc="small"]').click();assert(w.Arcade.round.done);w.document.getElementById('arcRefill').click();assert.equal(w.Arcade.practice,500);assert.equal(w.player.coins,500);assert(w.document.querySelectorAll('.arc-die svg').length===3);});
console.log('TOTAL '+n);dom.window.close();
