'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const {JSDOM}=require('jsdom');
const html=fs.readFileSync(require('path').join(__dirname,'../index.html'),'utf8');
const code=html.match(/<script>([\s\S]*?)<\/script>/)[1].replace(/\(function \(\) \{\s*'use strict';/,'').replace(/\}\)\(\);\s*$/,'').replace(/  init\(\);/,'');
const dom=new JSDOM(html.replace(/<script>[\s\S]*?<\/script>/,''),{url:'https://example.test',runScripts:'outside-only'});
const w=dom.window; w.setTimeout=()=>0; w.requestAnimationFrame=()=>0;
w.eval(code);
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}
test('新版独立key旧档不覆盖',()=>{w.localStorage.setItem(w.LEGACY_SAVE_KEY,'{"old":true}');w.loadAllSaves();assert.equal(w.localStorage.getItem(w.LEGACY_SAVE_KEY),'{"old":true}');assert.notEqual(w.LEGACY_SAVE_KEY,w.SAVE_KEY_ALL);});
test('单机新档直接500且无领取接口',()=>{assert.equal(w.START_COINS,500);assert.equal(w.player.coins,500);assert.equal(w.SAVE_VERSION,16);assert(!html.includes('GRANT_ENDPOINT'));assert(!w.document.getElementById('initialGrant'));});
test('每日按游戏各一项再加通用项，总额随表计算',()=>{w.ensureDailyTasks();const pool=w.TASK_POOL;
 assert.equal(w.player.dailyTasks.ids.length,pool.length,'每日项数应等于任务池（每游戏一项 + 通用一项）');
 w.GAME_IDS.forEach(g=>assert.ok(w.player.dailyTasks.ids.includes('d15_'+g),g+' 应有日常'));
 assert.equal(w.player.dailyTasks.ids.reduce((s,id)=>s+w.getDailyTaskById(id).reward,0),pool.reduce((s,t)=>s+t.reward,0));});
test('每日领取防重复和越权',()=>{const total=w.player.dailyTasks.ids.reduce((s,id)=>s+w.getDailyTaskById(id).reward,0);let ids=w.player.dailyTasks.ids;ids.forEach(id=>w.player.dailyProgress[id]=9999);let before=w.player.coins;ids.forEach(id=>w.claimDaily(id));ids.forEach(id=>w.claimDaily(id));assert.equal(w.player.coins-before,total);w.player.dailyProgress['not-a-task']=999;assert.equal(w.claimDaily('not-a-task'),false);assert.equal(w.player.coins-before,total);});
test('25周常总额1242且奖励30至78',()=>{assert.equal(w.WEEKLY_TASKS.length,25);assert.equal(w.WEEKLY_TASKS.reduce((s,t)=>s+t.reward,0),1242);w.WEEKLY_TASKS.forEach(t=>assert(t.reward>=30&&t.reward<=78));});
test('已有余额进度及领取标记刷新保留，全部周常不超1242',()=>{w.ensureWeekly();w.WEEKLY_TASKS.forEach(t=>w.player.weekly.progress[t.id]=t.target);const before=w.player.coins;w.WEEKLY_TASKS.forEach(t=>w.claimWeekly(t.id));assert.equal(w.player.coins-before,1242);w.saveAllSaves(true);w.player=null;w.allSaves=null;w.loadAllSaves();assert.equal(w.player.coins,before+1242);w.WEEKLY_TASKS.forEach(t=>{assert(w.player.weekly.claimed[t.id]);assert.equal(w.claimWeekly(t.id),false);});w.player.weekly={key:'expired',progress:{},claimed:{}};w.ensureWeekly();});
test('同族事件真实更新各阶段并防重复领取',()=>{w.ensureWeekly();w.recordGrowth15('holdem',{hands:30},'easy');let list=w.WEEKLY_TASKS.filter(t=>t.game==='holdem'&&t.event==='hands');assert(list.every(t=>w.player.weekly.progress[t.id]===Math.min(30,t.target)));let before=w.player.coins;assert(w.claimWeekly(list[0].id));assert(!w.claimWeekly(list[0].id));assert.equal(w.player.coins-before,list[0].reward);});
test('成就1000项ID唯一奖励合法',()=>{assert.equal(w.ACHIEVEMENTS.length,1000);assert.equal(new Set(w.ACHIEVEMENTS.map(a=>a.id)).size,1000);assert(w.ACHIEVEMENTS.every(a=>a.reward>=10&&a.reward<=2000));});
test('成就独立领取且分页不渲染1000项',()=>{let a=w.ACHIEVEMENTS.find(a=>a.metric);w.profile15(a.game).metrics[a.event]=a.target;let before=w.player.coins;assert(w.claimAchievement(a.id));assert(!w.claimAchievement(a.id));assert.equal(w.player.coins-before,a.reward);w.renderAchList();assert(w.document.querySelectorAll('.ach-item').length<=20);});
test('新手盲注10/20',()=>{assert.equal(w.DIFFICULTY_CONFIG.easy.sb,10);assert.equal(w.DIFFICULTY_CONFIG.easy.bb,20);});
test('独立浏览器存档隔离且可直接开局',()=>{const other=new JSDOM(html.replace(/<script>[\s\S]*?<\/script>/,''),{url:'https://example.test',runScripts:'outside-only'});other.window.setTimeout=()=>0;other.window.requestAnimationFrame=()=>0;other.window.eval(code);other.window.loadAllSaves();assert.equal(other.window.player.coins,500);assert.notEqual(other.window.player.coins,w.player.coins);assert.equal(other.window.localStorage.getItem(w.LEGACY_SAVE_KEY),null);other.window.startGame=()=>{};assert(other.window.tryEnterGame('easy'));other.window.close();});
test('刷新不重置余额，新建档500',()=>{w.player.coins=321;w.saveAllSaves(true);w.player=null;w.allSaves=null;w.loadAllSaves();assert.equal(w.player.coins,321);w.createNewSaveAt(2);assert.equal(w.player.coins,500);assert.equal(w.allSaves.slots[1].player.coins,321);});
test('人机对局免费入场：空钱包拒绝，499可进且不扣门票',()=>{const start=w.startGame;let entered=0;w.startGame=()=>entered++;w.App.mode='quick';w.G.active=false;w.player.coins=0;assert.equal(w.tryEnterGame('easy'),false);assert.equal(entered,0);w.player.coins=499;assert.equal(w.tryEnterGame('easy'),true);assert.equal(entered,1);assert.equal(w.player.coins,499,'人机对局不应扣门票');w.startGame=start;});
test('AI低于500替换为新身份，500和赢家保留，人类不补币',()=>{w.App.difficulty='easy';w.initPlayers();const old=w.G.players.slice();old[0].chips=499;old[1].chips=499;old[2].chips=500;old[3].chips=800;old[1].psych.tilt=99;const changed=w.refreshLowStackOpponents();assert.equal(changed.length,1);assert.equal(w.G.players[1].id,1);assert.equal(w.G.players[1].chips,500);assert.notEqual(w.G.players[1].name,old[1].name);assert.notEqual(w.G.players[1].psych,old[1].psych);assert.strictEqual(w.G.players[2],old[2]);assert.strictEqual(w.G.players[3],old[3]);assert.equal(w.G.players[0].chips,499);});
test('三个不足额AI同手补位且旧对象不改写',()=>{const old=w.G.players.slice(1);old.forEach((p,i)=>p.chips=[0,19,499][i]);assert.equal(w.refreshLowStackOpponents().length,3);assert(w.G.players.slice(1).every(p=>p.chips===500));assert.equal(new Set(w.G.players.map(p=>p.name)).size,4);assert.deepEqual(old.map(p=>p.chips),[0,19,499]);});
test('昵称随机源重复也能避免同桌及近期重名',()=>{const rand=w.randomInt;w.randomInt=()=>0;const names=[];for(let i=0;i<50;i++)names.push(w.randomAIName(names));assert.equal(new Set(names).size,50);w.randomInt=rand;});
test('安全随机整数拒绝取模尾部偏差且洗牌不依赖Math.random',()=>{const get=w.crypto.getRandomValues, math=w.Math.random;let calls=0;w.crypto.getRandomValues=a=>{a[0]=calls++===0?4294967295:7;return a;};assert.equal(w.randomInt(10),7);assert.equal(calls,2);w.crypto.getRandomValues=get;w.Math.random=()=>{throw Error('不得使用伪随机洗牌');};assert.equal(w.shuffle(w.makeDeck()).length,52);w.Math.random=math;assert.throws(()=>w.randomInt(0));});
test('10000次洗牌每副52张不重牌，首牌与花色分布烟测',()=>{let freq=Array(52).fill(0),suits=[0,0,0,0],seen=new Set();for(let i=0;i<10000;i++){let deck=w.shuffle(w.makeDeck());const keys=deck.map(c=>c.s*13+c.r-2);assert.equal(new Set(keys).size,52);seen.add(keys.join(','));freq[keys[0]]++;suits[deck[0].s]++;}assert.equal(seen.size,10000);assert(freq.every(n=>n>100&&n<300));assert(suits.every(n=>n>2200&&n<2800));console.log('首牌计数范围',Math.min(...freq),Math.max(...freq),'花色',suits);});
(async()=>{
  // 真实playHand在第一次动画等待前应已补位，不能到下注过程中才更换。
  w.App.difficulty='easy';w.player.coins=500;w.initPlayers();w.G.active=true;w.G.players[1].chips=10;
  const old=w.G.players[1], sleep=w.sleep;w.sleep=async()=>{w.G.active=false;};await w.playHand();
  assert.notStrictEqual(w.G.players[1],old);assert.equal(w.G.players[1].chips,500);w.sleep=sleep;count++;console.log('PASS 真实发牌前完成AI补位');
  w.player.coins=499;w.initPlayers();w.G.active=true;w.G.handSettled=true;w.G.settling=false;
  let dealt=0;const hand=w.playHand;w.playHand=async()=>{dealt++;w.G.active=false;};await w.runGameLoop();
  assert.equal(dealt,1);assert.equal(w.player.coins,499);w.playHand=hand;count++;console.log('PASS 人机对局低筹码不踢出，正常发牌');
  console.log('TOTAL '+count);dom.window.close();
})().catch(e=>{console.error(e);process.exitCode=1;dom.window.close();});
